Remove the bloat and switch to yarn

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,27 +14,19 @@ jobs:
         uses: actions/cache@v1
         with:
           path: ~/.npm
-          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
           restore-keys: |
             ${{ runner.os }}-node-
 
       - name: Install
-        run: npm ci
-
-      - name: Format
-        run: npm run format
+        run: yarn install --frozen-lockfile
 
       - name: Build
-        run: |
-          npm run build
-          npm run package
-
-      - name: Test
-        run: npm run test
+        run: npm run build
 
       - name: Check for changes
         run: |
           git diff --exit-code --stat -- . ':!node_modules' \
-          || (echo "##[error] found changed files after build. please 'npm run all'" \
+          || (echo "##[error] found changed files after build. please 'npm run build'" \
                   "and check in all changes" \
               && exit 1)
